### ISSUE TITLE
AttributeError: module 'val' has no attribute 'run'

### ISSUE THREAD

**Issue by mattlaued** [wsynuiag/NAPGaurd#1]
I couldn't find a requirements.txt so I downloaded the packages as I bumped into errors. There's an error that comes from the val v0.6 package (pip installed for line 46 of train_NAPGuard.py). The error message (as below) comes after training for 1 epoch, which looks like it's from the validation error code.

I ran `python train_NAPGuard.py --AFAL` and got the below output:
```
Plotting labels to runs\NAPGuard_train\exp\labels.jpg... 
Image sizes 416 train, 416 val
Using 0 dataloader workers
Logging results to runs\NAPGuard_train\exp
Starting training for 200 epochs...

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
      0/199      2.71G    0.08581    0.01959          0          1        416: 100%|██████████| 352/352 01:49
Traceback (most recent call last):
  File "<redacted>\NAPGaurd\train_NAPGuard.py", line 696, in <module>
    main(opt)
  File "<redacted>\NAPGaurd\train_NAPGuard.py", line 590, in main
    train(opt.hyp, opt, device, callbacks)
  File "<redacted>\NAPGaurd\train_NAPGuard.py", line 409, in train
    results, maps, _ = validate.run(data_dict,
                       ^^^^^^^^^^^^
AttributeError: module 'val' has no attribute 'run'
```

Did I download the wrong package? Seems like a problem with val. Thanks!

**Comment by wsynuiag** [comment]
Sorry from the mistake. We've changed the line 46 of train_NAPGuard.py  into:
`import val_NAPGuard as validate  # for end-of-epoch mAP`
Thanks for your comments.
