### ISSUE TITLE
Are there pre-trained weights of the patch detector that I can download?

### ISSUE THREAD

**Issue by mattlaued** [wsynuiag/NAPGaurd#2]
I tried using the models/yolov5s.pt directly for `python val_NAPGuard.py --NFSI --data data/patch.yaml --weights models/yolov5s.pt`, but had an error that it has 80 classes rather than the 1 patch class. It seems like I need to train that model with train_NAPGuard.py to obtain the eventual model that the authors used.

Instead of re-training, is there an existing trained patch detector model that I can use?

**Comment by wsynuiag** [comment]
Dear mattlaued,

We've uploaded our weights.
