### ISSUE TITLE
Question about metrics AP@0.5

### ISSUE THREAD

**Issue by Gandolfczjh** [wsynuiag/NAPGaurd#4]
Which class do the metrics in the paper refer to, the "person" or the "patch"? If it refers to "person," how does the patch detector proposed in the paper calculate the AP for "person"? If it refers to "patch," how do the data in the paper compare with other methods? I hope the authors can clarify this, thank you. 👍

**Comment by wsynuiag** [comment]
Dear Gandolfczjh,
AP@0.5 refers to "patch".  For methods that generate masks, we convert the generated masks into bounding boxes to calculate AP@0.5 approximately.

**Comment by Gandolfczjh** [comment]
I understand, thank you for your response.
